[package]
name = "basilisk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.0"
rpassword = "7.3.1"
serpent = "0.5.1"
